ImportSpecification ::= module VersionList? ('=' FilteredImportList )?
VersionList ::= ('(' version (',' version)* ')')
FilteredImportList ::= '(' (((name ('→' rename)? | '-' excludedName) (',' (name ('→' rename)? | '-' excludedName))*)  (','? '…')? | '…'?) ')'
