ImportSpecification ::= module VersionList? ('=' CustomImportRulesList )?
VersionList ::= ('(' version (',' version)* ')')
CustomImportRulesList ::= '(' (((name ('→' rename)? | '-' excludedName) (',' (name ('→' rename)? | '-' excludedName))*)  (','? '…')? | '…'?) ')'
